### ISSUE TITLE
Pause functionality

### ISSUE THREAD

**Issue by QaiserAbbas** [AppDevGuy/OSSSpeechKit#28]
Hi, 
I am creating an app which recognise text using OSSSpeechKit. 
I have an issue 
App recognise text and show in textview 
user also has ability to stop the recognition and resume again. 
but then last recognised text is lost. 

Can we have a pause functionality?

**Comment by AppDevGuy** [comment]
Hi @QaiserAbbas thanks for using my pod. Pause functionality could be a feature in future. It's not in my immediate sights but if you'd like to implement it, feel free to clone to repo and when you're ready, create a pull request.

For now I'd recommend implementing a solution that stores the recorded words until your speech session is completed.

**Comment by SeanAHI** [comment]
Closing ticket. If it appears in future as a feature request or on the dev road map will link.
