### ISSUE TITLE
OSSSpeechKit Stop listening after some time

### ISSUE THREAD

**Issue by QaiserAbbas** [AppDevGuy/OSSSpeechKit#29]
OSSSpeechKit Stop listening after some time
didFinishListening is called. 
Any solution for this?

**Comment by AppDevGuy** [comment]
This is due to Apple enforcing a limit on how long the microphone can remain active while utilising the speech service - from memory it's around 60 seconds.

A potential solution would be to invoke a call to start recording again, however, there is likely to be a short delay.

**Comment by SeanAHI** [comment]
Closing stale ticket due to no response.
