### ISSUE TITLE
Support for Objective-C

### ISSUE THREAD

**Issue by EddieLukeAtmey** [AppDevGuy/OSSSpeechKit#40]
I tried to add this library to our project (a mix of swift and objective-c) and tried to call the prop / func from objective-c class, it raised a compile error: `Property 'shared' not found on object of type 'OSSSpeech`.

To support Obj-C code, you'll need to add `@objc` to the class. If it sounds plausible, I can make a PR for that. Anyway, I want to ask first if this is a good thing.

**Comment by EddieLukeAtmey** [comment]
Thanks for your confirmation. I guess if I really want to use this, I'd better fork a new version and add support myself. If I write a wrapper for a wrapper, it's kinda unnecessary and obsolete, don't you think? Anyway, I think I should close this as not supported / unintended.

**Comment by AppDevGuy** [comment]
No problem, thanks for checking out my library, appreciate it.
