### ISSUE TITLE
How to add some delay between two speakText 

### ISSUE THREAD

**Issue by Abhishek2611** [AppDevGuy/OSSSpeechKit#5]

**Comment by AppDevGuy** [comment]
Hi @Abhishek2611 I am not sure that I understand what you mean. Could you please add a description to your issue regarding what you have tried and what you would like to happen? 

If you are referring to how fast the speech is, you can control this with the `utterance.rate` variable.

Eg. 
```swift
// Speak fast
utterance.rate = 1.5
// Speak slow
utterance.rate = 0.05
```

**Comment by AppDevGuy** [comment]
Closing due to no response.
